import Head from 'next/head'
import { useEffect, useState } from 'react';
import { Splash } from '@/molecules/Splash';
import { LocationHeader } from '@/molecules/LocationHeader';
import { SearchBar } from '@/molecules/SearchBar';
import { StoriesTray } from '@/molecules/StoriesTray';

export default function Home() {
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 2500);
  }, []);

  return (
    <>
      <Head>
        <title>Dineout Vibes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-full'>
        {loading && false ? <Splash /> : <div>
          <LocationHeader />
          <div className='px-2 mt-6'>
            <StoriesTray />
          </div>
        </div>}
      </main>
    </>
  )
}
